# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 42d5ae1db3f4b3e0c569ad446b78d07bb8e915d10a242a44f4dcb6bb72156c9f8588e92e638837970a1fe45c96f1014c6f2be9108bb865e56d72c336904534a6

test:
  secret_key_base: a14e17305c413c960dff897dc9850f388f29814506f261d3f89e7edeede772ae7182246c86d8a0a1da57d29fcf10055c3b1a7e3ecf66f69d77d7e7552ac27370

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
